import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div>
      <Head>
        <title>fwywd_lp_teamB</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <div>
          <img src='entre.png' width='1440' />
        </div>
        <h2 className='mt-5 ml-5 text-4xl'>実際の活動</h2>
        <div className='flex justify-evenly'>
          <div>
            <h4 className='flex justify-center text-3xl'>1.ビジネス力×技術力の強化</h4>
            <div className='flex justify-between items-center'>
              <img src='1.png' width='150' />
              <img src='2.png' width='150' />
              <img src='3.png' width='150' />
            </div>
          </div>
          <div>
            <h4 className='flex justify-center text-3xl'>2.熱意が高い仲間とのつながり</h4>
            {/* ここにcomunication2の画像を挿入 */}
          </div>
        </div>
      </main>
    </div>
  );
}
